services:
  mysql:
    image: mysql:9
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: mudar123
      # MYSQL_DATABASE: app
      # MYSQL_USER: app
      # MYSQL_PASSWORD: mudar123
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql

volumes: 
  mysql_data:
