services:
  mongodb:
    image: mongo:8-noble
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mudar123
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db

volumes: 
  mongodb_data:
